"""empty message

Revision ID: 01b5ba26eaa6
Revises: 880e11aa80ee
Create Date: 2021-07-05 11:38:48.703564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b5ba26eaa6'
down_revision = '880e11aa80ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_uid_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uid_token', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
