"""empty message

Revision ID: 71ae7cc51200
Revises: fdbd7d7ff131
Create Date: 2021-06-17 14:16:26.553448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ae7cc51200'
down_revision = 'fdbd7d7ff131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid_token', sa.String(length=1000), nullable=True))
    op.drop_column('users', 'user_uid_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uid_token', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('users', 'uid_token')
    # ### end Alembic commands ###
