"""empty message

Revision ID: 7be16ab20a08
Revises: 80dba4855678
Create Date: 2021-06-05 11:01:14.583961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be16ab20a08'
down_revision = '80dba4855678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_user_uid', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firebase_user_uid')
    # ### end Alembic commands ###
