"""empty message

Revision ID: 80dba4855678
Revises: c45f72e01ea3
Create Date: 2021-06-04 18:07:40.019093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dba4855678'
down_revision = 'c45f72e01ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cloud_file_name', sa.String(length=56), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cloud_file_name')
    # ### end Alembic commands ###
