"""empty message

Revision ID: a187443dbe9b
Revises: 7c1a04eb8c8e
Create Date: 2021-05-03 17:47:06.347477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a187443dbe9b'
down_revision = '7c1a04eb8c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_id')
    # ### end Alembic commands ###
