"""empty message

Revision ID: e75285547c2f
Revises: 7be16ab20a08
Create Date: 2021-06-05 12:32:33.700803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75285547c2f'
down_revision = '7be16ab20a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uid_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_uid_token')
    # ### end Alembic commands ###
