"""empty message

Revision ID: fdbd7d7ff131
Revises: e75285547c2f
Create Date: 2021-06-08 13:43:08.777002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbd7d7ff131'
down_revision = 'e75285547c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_photo_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_photo_id')
    # ### end Alembic commands ###
